# Generated by Django 3.2 on 2021-04-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='grades',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
