# Generated by Django 3.2 on 2021-04-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='grades',
            field=models.CharField(default='Ask office for grades', max_length=200),
        ),
    ]
