# Generated by Django 3.2 on 2021-04-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='new',
            name='slug',
            field=models.SlugField(default='for_post_identification', max_length=20),
        ),
    ]
