# Generated by Django 3.2 on 2021-05-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20210501_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(default='school_slug', max_length=20),
        ),
    ]
